### ISSUE TITLE
tournament:import -i not working

### ISSUE THREAD

**Issue by priverop** [deMenschRutger/SmashArchive#5]
Following the docs, after importing splice-14 I try:

`bin/console app:tournament:import -i 1`

And I get:

`The "-i" option does not exist.`

How can I solve that?

**Comment by priverop** [comment]
The correct command is `app:event:standings:generate`

**Comment by priverop** [comment]
Actually it's `bin/console app:event:standings:generate --all ALL`

**Comment by deMenschRutger** [comment]
The last `ALL` can actually be any value that's truthy. Also, be aware that generating standings for all events on a database that contains many tournaments will take a long time.

Anyway, this is correctly described in the README now.
